export const PAYMENT_METHOD_ONLINE = "ONLINE";
export const PAYMENT_METHOD_CASH = "CASH";
export const PAYMENT_METHOD_CARD = "CARD";

export const PAYMENT_STATUS_PENDING = "PENDING";
export const PAYMENT_STATUS_SUCCESS = "SUCCESS";
export const PAYMENT_STATUS_FAILED = "FAILED";



